:concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - default

:scheduler:
  :schedule:
    adjust_price_by_inventory:
      cron: '*/5 * * * *'
      class: 'AdjustPriceByInventoryJob'
    adjust_price_by_demands:
      cron: '*/5 * * * *'
      class: 'AdjustPriceByDemandJob'
    adjust_price_by_competition:
      cron: '0 */1 * * *'
      class: 'AdjustPriceByCompetitionJob'



